name: Deploy AWS Glue Script

on:
  push:
    branches:
      - develop
      - test
      - main
    paths:
      - scripts/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "REGION=ap-south-1" >> $GITHUB_ENV
            echo "S3_BUCKET=my-dev-bucket" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=glue-hello-world-dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "test" ]]; then
            echo "REGION=ap-south-1" >> $GITHUB_ENV
            echo "S3_BUCKET=my-test-bucket" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=glue-hello-world-test" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "REGION=ap-south-1" >> $GITHUB_ENV
            echo "S3_BUCKET=my-prod-bucket" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=glue-hello-world-prod" >> $GITHUB_ENV
          else
            echo "Unknown branch, defaulting to dev config"
            echo "REGION=ap-south-1" >> $GITHUB_ENV
            echo "S3_BUCKET=my-dev-bucket" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=glue-hello-world-dev" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Upload script to S3
        run: |
          echo "Uploading script to S3 bucket: $S3_BUCKET"
          aws s3 cp scripts/hello_world.py s3://$S3_BUCKET/scripts/hello_world.py

      - name: Start AWS Glue job
        run: |
          echo "Starting AWS Glue job: $GLUE_JOB_NAME"
          aws glue start-job-run --job-name $GLUE_JOB_NAME
