name: Glue ETL Deployment

on:
  push:
    branches:
      - develop
      - test
      - main

env:
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: trendytech-tutorial-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------
      # 1️⃣ Set environment variables based on branch
      # -------------------------------
      - name: Set environment variables
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "ENV_NAME=dev" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=hello-world-dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
            echo "ENV_NAME=test" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=hello-world-test" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENV_NAME=master" >> $GITHUB_ENV
            echo "GLUE_JOB_NAME=hello-world-prod" >> $GITHUB_ENV
          else
            echo "Branch not recognized. Exiting."
            exit 1
          fi

      # -------------------------------
      # 2️⃣ Configure AWS credentials
      # -------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------------------
      # 3️⃣ Upload Python script to environment folder in S3
      # -------------------------------
      - name: Upload hello_world.py to S3
        run: |
          aws s3 cp scripts/hello_world.py s3://${S3_BUCKET}/${ENV_NAME}/hello_world.py

      # -------------------------------
      # 4️⃣ Trigger Glue job
      # -------------------------------
      - name: Start AWS Glue Job
        run: |
          JOB_RUN_ID=$(aws glue start-job-run --job-name ${GLUE_JOB_NAME} --query 'JobRunId' --output text)
          echo "Started Glue job ${GLUE_JOB_NAME} with JobRunId: ${JOB_RUN_ID}"

      # -------------------------------
      # 5️⃣ (Optional) Wait for Glue job completion
      # -------------------------------
      - name: Wait for Glue Job to complete
        run: |
          echo "Waiting for Glue job to finish..."
          aws glue get-job-run --job-name ${GLUE_JOB_NAME} --run-id ${JOB_RUN_ID} --query 'JobRun.State'
